database_mysql:
  uri: root:123456@tcp(127.0.0.1:3306)/chat?charset=utf8&parseTime=True&loc=Local

database_mongo:
  uri:mongodb://localhost:27017"

app:
  logFile: log/gin.log
  httpPort: 8080
  httpUrl: 127.0.0.1:8080
